version: 0.1.{build}

configuration: Release

# Start SQL Server 2016
services:
  - mssql2016

# Restore NuGet packages & set up SQL Server for the tests
before_build:
  - nuget restore
  - ps: .\AppVeyorSetupSqlServer.ps1

artifacts:
  - path: SqlServerHelpers\bin\Release\SqlServerHelpers.dll
    name: SqlServerHelpers.dll
  - path: '**\SqlServerHelpers*.nupkg'
  - path: NuGet\SqlServerHelpers.nuspec

# PowerShell script to deploy to NuGet (runs after any unit tests, if they pass)
after_test:
  - ps: .\NuGet\pack.ps1

# Publish to NuGet
deploy:
  provider: NuGet
  api_key:
    secure: fy1qFrz8kHfWX2AnOMd2BuzLgDb2MMTj2JrryhAe4n84l2smPM4ohi9NRZZ0MAig
  artifact: /.*\.nupkg/